# Generated by Django 5.1.7 on 2025-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
