# Generated by Django 5.1.7 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_physicalactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacklog',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
