# Generated by Django 5.1.7 on 2025-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_snacklog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacklog',
            name='carbohydrates',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='snacklog',
            name='fat',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='snacklog',
            name='fiber',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='snacklog',
            name='protein',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='snacklog',
            name='sugar',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='snacklog',
            name='calories',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
