# Generated by Django 5.1.7 on 2025-05-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reteta',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='RetetaIngrediente',
            new_name='RecipeIngredient',
        ),
    ]
