# Generated by Django 5.1.7 on 2025-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('met_low', models.FloatField()),
                ('met_moderate', models.FloatField()),
                ('met_high', models.FloatField()),
            ],
        ),
    ]
