# Generated by Django 5.1.7 on 2025-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
