# Generated by Django 5.1.7 on 2025-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_category_alter_recipe_cuisine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='calories_per_unit',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='unit',
        ),
        migrations.AddField(
            model_name='snack',
            name='calories_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
