# Generated by Django 5.1.7 on 2025-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_snack_calories_per_unit_remove_snack_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivity',
            name='information',
            field=models.TextField(blank=True, help_text='Describe what each intensity means, e.g. speed or effort.'),
        ),
    ]
