# Generated by Django 5.2.1 on 2025-05-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_physicalactivity_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
