# Generated by Django 5.2.1 on 2025-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_ingredient_calories_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='gram', max_length=50),
            preserve_default=False,
        ),
    ]
