# Generated by Django 5.2.1 on 2025-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(default='gram', max_length=25),
            preserve_default=False,
        ),
    ]
