# Generated by Django 5.2.3 on 2025-06-15 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
